// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/transaction_type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionType) Reset() {
	*x = TransactionType{}
	mi := &file_proto_transaction_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionType) ProtoMessage() {}

func (x *TransactionType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionType.ProtoReflect.Descriptor instead.
func (*TransactionType) Descriptor() ([]byte, []int) {
	return file_proto_transaction_type_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransactionType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransactionTypeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionType *TransactionType       `protobuf:"bytes,1,opt,name=TransactionType,proto3" json:"TransactionType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionTypeResponse) Reset() {
	*x = TransactionTypeResponse{}
	mi := &file_proto_transaction_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionTypeResponse) ProtoMessage() {}

func (x *TransactionTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionTypeResponse.ProtoReflect.Descriptor instead.
func (*TransactionTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_type_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionTypeResponse) GetTransactionType() *TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

type CreateTransactionTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionTypeRequest) Reset() {
	*x = CreateTransactionTypeRequest{}
	mi := &file_proto_transaction_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionTypeRequest) ProtoMessage() {}

func (x *CreateTransactionTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_type_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransactionTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTransactionTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_transaction_type_proto protoreflect.FileDescriptor

const file_proto_transaction_type_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/transaction_type.proto\x12\x02pb\"W\n" +
	"\x0fTransactionType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"X\n" +
	"\x17TransactionTypeResponse\x12=\n" +
	"\x0fTransactionType\x18\x01 \x01(\v2\x13.pb.TransactionTypeR\x0fTransactionType\"T\n" +
	"\x1cCreateTransactionTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2p\n" +
	"\x16TransactionTypeService\x12V\n" +
	"\x15CreateTransactionType\x12 .pb.CreateTransactionTypeRequest\x1a\x1b.pb.TransactionTypeResponseB\rZ\vinternal/pbb\x06proto3"

var (
	file_proto_transaction_type_proto_rawDescOnce sync.Once
	file_proto_transaction_type_proto_rawDescData []byte
)

func file_proto_transaction_type_proto_rawDescGZIP() []byte {
	file_proto_transaction_type_proto_rawDescOnce.Do(func() {
		file_proto_transaction_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_type_proto_rawDesc), len(file_proto_transaction_type_proto_rawDesc)))
	})
	return file_proto_transaction_type_proto_rawDescData
}

var file_proto_transaction_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_transaction_type_proto_goTypes = []any{
	(*TransactionType)(nil),              // 0: pb.TransactionType
	(*TransactionTypeResponse)(nil),      // 1: pb.TransactionTypeResponse
	(*CreateTransactionTypeRequest)(nil), // 2: pb.CreateTransactionTypeRequest
}
var file_proto_transaction_type_proto_depIdxs = []int32{
	0, // 0: pb.TransactionTypeResponse.TransactionType:type_name -> pb.TransactionType
	2, // 1: pb.TransactionTypeService.CreateTransactionType:input_type -> pb.CreateTransactionTypeRequest
	1, // 2: pb.TransactionTypeService.CreateTransactionType:output_type -> pb.TransactionTypeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_transaction_type_proto_init() }
func file_proto_transaction_type_proto_init() {
	if File_proto_transaction_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_type_proto_rawDesc), len(file_proto_transaction_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_type_proto_goTypes,
		DependencyIndexes: file_proto_transaction_type_proto_depIdxs,
		MessageInfos:      file_proto_transaction_type_proto_msgTypes,
	}.Build()
	File_proto_transaction_type_proto = out.File
	file_proto_transaction_type_proto_goTypes = nil
	file_proto_transaction_type_proto_depIdxs = nil
}
