// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/transaction_type.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionTypeService_CreateTransactionType_FullMethodName = "/pb.TransactionTypeService/CreateTransactionType"
)

// TransactionTypeServiceClient is the client API for TransactionTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionTypeServiceClient interface {
	CreateTransactionType(ctx context.Context, in *CreateTransactionTypeRequest, opts ...grpc.CallOption) (*TransactionTypeResponse, error)
}

type transactionTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionTypeServiceClient(cc grpc.ClientConnInterface) TransactionTypeServiceClient {
	return &transactionTypeServiceClient{cc}
}

func (c *transactionTypeServiceClient) CreateTransactionType(ctx context.Context, in *CreateTransactionTypeRequest, opts ...grpc.CallOption) (*TransactionTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionTypeResponse)
	err := c.cc.Invoke(ctx, TransactionTypeService_CreateTransactionType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionTypeServiceServer is the server API for TransactionTypeService service.
// All implementations must embed UnimplementedTransactionTypeServiceServer
// for forward compatibility.
type TransactionTypeServiceServer interface {
	CreateTransactionType(context.Context, *CreateTransactionTypeRequest) (*TransactionTypeResponse, error)
	mustEmbedUnimplementedTransactionTypeServiceServer()
}

// UnimplementedTransactionTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionTypeServiceServer struct{}

func (UnimplementedTransactionTypeServiceServer) CreateTransactionType(context.Context, *CreateTransactionTypeRequest) (*TransactionTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransactionType not implemented")
}
func (UnimplementedTransactionTypeServiceServer) mustEmbedUnimplementedTransactionTypeServiceServer() {
}
func (UnimplementedTransactionTypeServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionTypeServiceServer will
// result in compilation errors.
type UnsafeTransactionTypeServiceServer interface {
	mustEmbedUnimplementedTransactionTypeServiceServer()
}

func RegisterTransactionTypeServiceServer(s grpc.ServiceRegistrar, srv TransactionTypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionTypeService_ServiceDesc, srv)
}

func _TransactionTypeService_CreateTransactionType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionTypeServiceServer).CreateTransactionType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionTypeService_CreateTransactionType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionTypeServiceServer).CreateTransactionType(ctx, req.(*CreateTransactionTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionTypeService_ServiceDesc is the grpc.ServiceDesc for TransactionTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransactionTypeService",
	HandlerType: (*TransactionTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransactionType",
			Handler:    _TransactionTypeService_CreateTransactionType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction_type.proto",
}
